# Generated by Django 5.2.6 on 2025-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('lost', 'Lost'), ('found', 'Found')], max_length=10),
        ),
    ]
