# Generated by Django 5.1.5 on 2025-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pet_status_favouritepet_userstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
