# Generated by Django 5.1.5 on 2025-10-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_petreport_admin_comment'),
    ]

    operations = [
    ]
