# Generated by Django 5.1.5 on 2025-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20251008_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available for Adoption'), ('adopted', 'Adopted'), ('lost', 'Lost'), ('found', 'Found'), ('reunited', 'Reunited'), ('unavailable', 'Unavailable'), ('adopt', 'For Adoption')], default='unavailable', max_length=15),
        ),
    ]
